Script info: |
  Commands for setting up Cloud Connector in Digital.ai Release

connections:
  Digital.ai Release: ../login/connect.spec.yaml
  Digital.ai Platform: ../../platform/login/connect.spec.yaml
