Script info:
  description: Sends a greeting

Input schema:
  type: object
  properties:
    name:
      description: Your name
      default: there

Output: Hello ${input.name} from SpecScript HTTP Server!